[build]
builder = "DOCKERFILE"
dockerfilePath = "/Dockerfile.web"
watchPatterns = ["/platform/apps/web/**", "/platform/packages/shared/**", "/content/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
